name: Create Tag

on:
  push:
    branches:
      - main

jobs:
  build:
    if: "contains(github.event.head_commit.message, 'Release')"
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: christophebedard/tag-version-commit@v1
      id: tagger
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        version_regex: 'Release ([0-9]+\.[0-9]+\.[0-9]+)'
        version_tag_prefix: 'v'
        check_entire_commit_message: true
        version_assertion_command: 'grep -q "\"version\": \"$version\"" package.json'
    - name: Tag output
      run: echo "${{ steps.tagger.outputs }}"
