name: Create Tag

on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Tag
      id: tagger-action
      uses: christophebedard/tag-version-commit@v1
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        version_regex: 'Release ([0-9]+\.[0-9]+\.[0-9]+)'
        version_tag_prefix: 'v'
        check_entire_commit_message: true
        version_assertion_command: 'grep -q "\"version\": \"$version\"" package.json'
    - name: Tag output
      run: echo 'The time was ${{ steps.tagger-action.outputs.tag }}.'
