name: Create Tag

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: christophebedard/tag-version-commit@v1
      id: tagger
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        version_regex: 'Release ([0-9]+\.[0-9]+\.[0-9]+)'
        version_tag_prefix: 'v'
        check_entire_commit_message: true
        version_assertion_command: 'grep -q "\"version\": \"$version\"" package.json'
    - name: Tag Empty
      if: ${{ steps.previous_step.outputs.tagname == '' }}
      run: echo "Empty tag ${{ steps.tagger.outputs.version }}"
    - name: Tag Created
      if: ${{ !steps.previous_step.outputs.tagname == '' }}
      run: echo "Tag created is ${{ steps.previous_step.outputs.tagname }}"
