name: Releases

on:
  push:
    tags:
    - '*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
    - name: Release
      uses: ncipollo/release-action@v1
      with:
        allowUpdates: true
        commit: main
        token: ${{ secrets.GITHUB_TOKEN }}
