name: github-release

on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    if: "contains(github.event.head_commit.message, 'Releaseasdasdas')"
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
            token: ${{ secrets.GB_TOKEN }}
