name: npm-publish
on:
  push:
    branches:
      - main
jobs:
  release:
    if: "contains(github.event.head_commit.message, 'Releaseasdasdasd')"
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Archive Release
      uses: thedoctor0/zip-release@master
      with:
        type: 'zip'
        exclusions: '*.git* /*node_modules/* .editorconfig README.md'
        filename: 'master.zip'
    - name: Upload Release
      uses: ncipollo/release-action@v1
      with:
        artifacts: "master.zip"
        token: ${{ secrets.GITHUB_TOKEN }}
