name: release-package
on:
  push:
    tags:
      - '*'
jobs:
  release:
    if: github.event.pusher.name == github.event.repository.owner.name
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Check Tag Type
      id: tag-type
      run: |
        if ${{ contains(github.ref, 'alpha') }} || ${{ contains(github.ref, 'beta') }}; then
          echo '::set-output name=tag::next'
          echo '::set-output name=prerelease::true'
        else
          echo '::set-output name=tag::latest'
          echo '::set-output name=prerelease::false'
        fi
    - name: Print Tag Type
      run: |
        echo "Tag created ${{ steps.tag-type.outputs.tag }}"
        echo "Ref ${GITHUB_REF}"
    - name: Archive Release
      uses: thedoctor0/zip-release@master
      with:
        type: 'zip'
        exclusions: '*.git* /*node_modules/* .editorconfig README.md'
        filename: 'master.zip'
    - name: Upload Release
      uses: ncipollo/release-action@v1
      with:
        artifacts: "master.zip"
        allowUpdates: "true"
        token: ${{ secrets.GB_TOKEN }}
        prerelease: ${{ steps.tag-type.outputs.prerelease }}
    - name: NPM Publish Package
      uses: JS-DevTools/npm-publish@v1
      with:
        tag: ${{ steps.tag-type.outputs.tag }}
        token: ${{ secrets.NPM_AUTH_TOKEN }}
